### ISSUE TITLE
CGI not required properly in prometheus/client/push.rb

### ISSUE THREAD

**Issue by jimbali** [prometheus/client_ruby#202]
On Ruby 2.7.1 I get this error when trying to push to a gateway:

```
irb(main):003:0> require 'prometheus/client'
=> true
irb(main):004:0> require 'prometheus/client/push'
=> true
irb(main):005:0> registry = Prometheus::Client.registry
irb(main):006:0> Prometheus::Client::Push.new('test-job').add(registry)
Traceback (most recent call last):
       16: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
       15: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
       14: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
       13: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
       12: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       11: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
       10: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
        9: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
        8: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
        7: from /Users/jbailey/.rbenv/versions/2.7.1/bin/irb:23:in `<top (required)>'
        6: from /Users/jbailey/.rbenv/versions/2.7.1/bin/irb:23:in `load'
        5: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        4: from (irb):6
        3: from (irb):6:in `new'
        2: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/prometheus-client-2.1.0/lib/prometheus/client/push.rb:28:in `initialize'
        1: from /Users/jbailey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/prometheus-client-2.1.0/lib/prometheus/client/push.rb:71:in `build_path'
NameError (uninitialized constant Prometheus::Client::Push::CGI)
```

It seems that 'cgi' needs to be required at the top of the file. I haven't tried any other versions of Ruby so I don't know if it used to be required by default in previous versions or not.

**Comment by Sinjo** [comment]
@jimbali Sorry for how long it's taken, but there's a PR up at #217.
